topoguide/itineraires/urls.py
from django.urls import path
from itineraires import views

"""
Urls pour l'application itinéraires
"""
app_name = 'itineraires'
urlpatterns = [
    path('', views.ItineraireListView.as_view(),name='liste_itineraires'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('sortie/<int:pk>/', views.SortieView.as_view(), name='sortie'),
    path('sortie/creation/', views.CreationSortie, name='creation_sortie'),
    path('sortie/modification/<int:sortie_id>', views.ModificationSortie, name='modification_sortie'),
    path('sortie/suppression/<int:sortie_id>', views.SuppressionSortie, name='suppression_sortie'),
    path('searchResults/<str:filtre>', views.SearchResults, name='searchResults'),
    path('image/suppression/<int:image_id>', views.SuppressionImage, name='suppression_image'),

]

topoguide/topoguide/urls.py
from django import views
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('itineraires/',include('itineraires.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

topoguide/itineraires/forms.py
from dataclasses import fields
from django import forms
from .models import Commentaire, Image, Sortie


class SortieForm(forms.ModelForm):
    """
    Form générique de django utilisé pour création et modification
    """
    class Meta:
        # l'utilisateur a la main sur tout sauf le nom randonneur qui est lié à l'utilisateur connecté
        exclude = ('randonneur',)
        model = Sortie
        fields = '__all__'  # ['name']


class ImageForm(forms.ModelForm):
    """
    Form d'ajout de photo pour les sorties
    """

    # nécéssaire pour que l'on puisse modifier une sortie sans forcément ajouter de photo
    def __init__(self, *args, **kwargs):
        super(ImageForm, self).__init__(*args, **kwargs)
        self.fields['image'].required = False

    class Meta:
        # la sortie sera associée automatiquement
        model = Image
        fields = ['image', ]
        widgets = {
            'image': forms.ClearableFileInput(attrs={'multiple': True, 'name': 'images'})
        }


class CommentaireForm(forms.ModelForm):

    class Meta:
        model = Commentaire
        fields = ['texte']
        widgets = {
            'texte': forms.Textarea(attrs={'placeholder':'Comment a été votre sortie?','style':'height: 96px'})
        }

class StatusForm(forms.ModelForm):

    class Meta:
        model = Commentaire
        fields = ['status']
        widgets = {}

topoguide/itineraires/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import generic
from datetime import datetime
from itineraires.models import Itineraire, Sortie, Image, Commentaire
from .forms import CommentaireForm, ImageForm, SortieForm, StatusForm
from django.utils.decorators import method_decorator
from .forms import CommentaireForm, ImageForm, SortieForm
from .lastResearch import LastResearch
"""Toutes les vues affichent une barre de navigation à part le login"""


class ItineraireListView(generic.ListView):
    """
    Vue de la liste des itinéraires.
    """
    model = Itineraire


class DetailView(generic.UpdateView):

    """
    Vue représentant :
     - les détails de l'itinéraire choisi.
     - la liste des sorties sur cet itinéraire.

    """
    model = Itineraire
    template_name = 'itineraires/itineraire_detail.html'

    #nécéssaire pour pouvoir faire un formmixin dans une vue générique
    fileds = ['texte']
    form_class = CommentaireForm

    #on doit définir l'url de redirection en cas de form validé
    def get_success_url(self) -> str:
        #en cas de succes du form, on est redirigés vers l'itinéraire correspondant
        return '{}#itineraires'.format(reverse('itineraires:detail', kwargs={'pk': self.object.id}))

    # redéfinir get_context_data permet d'accéder aux sorties voulues
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        #utilisateur
        context['user']=self.request.user

        #sorties associées à l'itinéraire
        context["liste_sorties"] = Sortie.objects.filter(
            itineraire__id=self.object.id
        )

        #commentaires associées à l'itinéraire
        context["commentaires"] = Commentaire.objects.filter(
            itineraire__id=self.object.id
        )

        #toutes les images des sorties sur cet itinéraire
        context['photos'] = Image.objects.filter(
            sortie__itineraire__id=self.object.id
        )

        #form de nouveau commentaire
        context['form'] = CommentaireForm(initial={
                                          'utilisateur': self.request.user, 'itineraire': self.object, 'date': datetime.now(), 'status': 1})
        #form de changement de status
        context['status_form'] = StatusForm()
        return context




    #seuls les utilisateurs connectés peuvent POSTer des données
    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):

        self.object = self.get_object()

        #si le form POSTé est un changement de status
        if 'status' in request.POST:

            #recherche du commentaire sur lequel on veut effectuer le changement
            for com in Commentaire.objects.filter(itineraire__id=self.object.id):
                if "status-form-"+str(com.id) in request.POST:
                    com_id = com.id
                    break

            modified_com = Commentaire.objects.get(pk=com_id)

            form = StatusForm(request.POST,instance=modified_com)
 
            if request.user != modified_com.utilisateur:
                return self.form_invalid(form)
            #récupération de l'instance associée
            
            #validation
            if form.is_valid():
                com.status = request.POST['status']
                com.save()
                return HttpResponseRedirect(self.get_success_url())
        
        #si le form POSTé est un nouveau commentaire
        else:
            #récupération le form d commentaire avec la méthode django associée à form_class
            form = self.get_form()

            #validation
            if form.is_valid():
                Commentaire.objects.create(texte=form.cleaned_data['texte'],utilisateur=self.request.user, itineraire=self.object, date=datetime.now(), status=1)
                return self.form_valid(form)
        
        return self.form_invalid(form)
   

class SortieView(generic.DetailView):
    """
    Vue représentant les sorties.
    Accessible par url direct mais peu utile : on retrouve toutes les données nécéssaires dans DetailView.
    """
    model = Sortie
    template_name = 'itineraires/sorties.html'


@login_required
def CreationSortie(request):
    """
    Vue de création d'une sortie, en passant par les forms génériques de Django.

    """

    if request.method == 'GET':
        form = SortieForm()
    elif request.method == 'POST':
        form = SortieForm(request.POST)
        if form.is_valid():
            form.instance.randonneur = request.user
            form.save()
            # ce redirect renvoie vers l'itinéraire où l'on se trouvait avant la création de sortie
            return redirect('itineraires:detail', pk=form.cleaned_data['itineraire'].id)
    return render(request, 'itineraires/creation_sortie.html', {'form': form})


@login_required
def ModificationSortie(request, sortie_id):
    """
    Vue de modification d'une sortie, relativement similaire a la création.

    """

    # ici on vérifie que l'utilisateur qui modifie est le bon
    # Pas forcément utile pour un utilisateur normal car inaccessible dans le cas posant probleme sans trifouiller les urls, on n'est jamais trop prudents
    sortie_instance = Sortie.objects.get(pk=sortie_id)
    if request.user != sortie_instance.randonneur:
        return redirect('itineraires:detail', pk=sortie_instance.itineraire.id)
    if request.method == 'GET':
        form = SortieForm(instance=sortie_instance)
        imgForm = ImageForm(request.POST, request.FILES)
    elif request.method == 'POST':
        form = SortieForm(request.POST, instance=sortie_instance)
        imgForm = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            if imgForm.is_valid():
                # pour chaque image donnee on cree un objet
                images = request.FILES.getlist('image')
                for im in images:
                    Image.objects.create(
                        sortie=sortie_instance,
                        image=im
                    )

            # ce redirect renvoie vers l'itinéraire où l'on se trouvait avant la modification de sortie
            return redirect('itineraires:detail', pk=form.cleaned_data['itineraire'].id)
    return render(request, 'itineraires/modification_sortie.html', {'form': form, 'imgForm': imgForm})


@login_required
def SuppressionSortie(request, sortie_id):
    """
    Vue de suppression d'une sortie, relativement similaire a la création.

    """
    # ici on vérifie que l'utilisateur qui modifie est le bon
    sortie = Sortie.objects.get(pk=sortie_id)
    if request.user != sortie.randonneur:
        return redirect('itineraires:detail', pk=sortie.itineraire.id)
    # on garde l'id avant de supprimer pour pouvoir rediriger vers une page cohérente
    s_id = sortie.itineraire.id
    sortie.delete()
    return redirect('itineraires:detail', pk=s_id)


def SearchResults(request, filtre):
    """
    Vue qui affiche les résultats de la recherche
    
    """
    #Initialisation de la variable de contexte
    context = {}


    if filtre == "filtre-sortie":
        key_word = LastResearch.last_key_word
        trie = "aucun"
        if not LastResearch.last_filtre_models[0]:
            LastResearch.last_filtre_models[0] = True
        else :
            LastResearch.last_filtre_models[0] = False
        filtre_models = LastResearch.last_filtre_models
        context["filtre_models"] = filtre_models
        print(filtre_models)
        LastResearch.last_filtre = filtre
    if filtre == "filtre-itineraires":
        key_word = LastResearch.last_key_word
        trie = "aucun"
        if not LastResearch.last_filtre_models[1]:
            LastResearch.last_filtre_models[1] = True
        else :
            LastResearch.last_filtre_models[1] = False
        filtre_models = LastResearch.last_filtre_models
        context["filtre_models"] = filtre_models
        print(filtre_models)
        LastResearch.last_filtre = filtre
    if filtre == "filtre-commentaires":
        key_word = LastResearch.last_key_word
        trie = "aucun"
        if not LastResearch.last_filtre_models[2]:
            LastResearch.last_filtre_models[2] = True
        else :
            LastResearch.last_filtre_models[2] = False
        filtre_models = LastResearch.last_filtre_models
        context["filtre_models"] = filtre_models
        print(filtre_models)
        LastResearch.last_filtre = filtre

    #Mise à jour des context
    context["key_word"] = LastResearch.last_key_word
    context["liste_itinineraires"]=LastResearch.last_liste_itinineraires
    context["liste_sorties"]=LastResearch.last_liste_sorties
    context["liste_commentaires"]=LastResearch.last_liste_commentaires
    context["last_filtre_models"]=LastResearch.last_filtre_models



   

    #Si une recherche a été effectuée on renvoie les résulats sur la page searchResults.html
    if request.method == "POST": 


        if filtre == "all":
            #On récupères les données du formulaire de recherche
            LastResearch.last_filtre_models = [True, True, True]
            filtre_models = LastResearch.last_filtre_models
            print("filtre_models=",filtre_models)
            key_word = request.POST.get("search")
            trie ="aucun"
            context["key_word"]=key_word
            context["trie"]=trie
            context["filtre_models"] = filtre_models
        if filtre == "trie":
            filtre_models = LastResearch.last_filtre_models
            key_word = LastResearch.last_key_word
            trie = request.POST.get("trie")
            context["key_word"]=key_word
            context["trie"]=trie
            context["filtre_models"] = filtre_models
        if filtre == "filtre":
            key_word = request.POST.get("search-filtre")

topoguide/itineraires/templates/itineraires/creation_sortie.html
{# Permet la création de sorties, l'utilisateur n'est pas demandé, c'est automatiquement celui qui est logged in qui est mis #}

{% extends 'itineraires/navBar.html' %} {% load bootstrap5 %} 
{% block title%}Nouvelle Sortie{% endblock title%}
{% block content %}

<div class="container-fluid !direction !spacing">
  <form
    action="{% url 'itineraires:creation_sortie' %}"
    method="post"
    class="form"
  >
    <div class="container-fluid !direction !spacing pt-3">
      <h2>Sortie de {{request.user.username}}</h2>
    </div>
    {% csrf_token %} {% bootstrap_form form %} {% buttons %}
    <button type="submit" class="btn btn-success">Add</button>
    <a href="{% url 'itineraires:liste_itineraires' %}" class="btn btn-danger"
      >Cancel</a
    >
    {% endbuttons %}
  </form>
</div>

{% endblock content %}

topoguide/itineraires/templates/itineraires/itineraire_list.html
{# Très simple, affiche juste les itinéraires disponibles #}

{% extends 'itineraires/navBar.html' %} {% block content %}


<div class="container-fluid !justify !spacing p-3">
  
  <ul class="list-group pt-8">
    <div class="row">
        <div class="col-6 justify-content-md-center"><strong>Nom</strong></div>
        <div class="col-3"><strong>Difficulté</strong></div>
        <div class="col-3"><strong>Durée</strong></div>
      </div>
  {% for itineraire in object_list %}
  
  <a
  id="linkIti"
  class="row secondary"
  href="{% url 'itineraires:detail' itineraire.id %}"
  >
  <div class="col-6 link-dark">{{ itineraire.nom }}</div>
  <div class="col-3 link-dark">{{ itineraire.difficulte }}</div>
  <div class="col-3 link-dark">{{ itineraire.duree }}</div>
  </a>

{% endfor %}


</ul>
</div>

{% endblock %}

topoguide/itineraires/templates/itineraires/modification_sortie.html
{# Permet la modification des sorties, accessible seulement à l'utilisatuer ayant crée la sortie #}

{% extends 'itineraires/navBar.html' %} {% load bootstrap5 %} 
  {% block title %}Modifier la sortie{% endblock title%} {% block content %}
<div class="container-fluid !direction !spacing">
  <form
    method="post"
    class="form"
    enctype="multipart/form-data"
  >
    {% csrf_token %}
    {% bootstrap_form form%}    
    {% bootstrap_form imgForm%}    
    
    
    {% buttons %}
    <button type="submit" class="btn btn-primary">Update</button>
    <a href="{% url 'itineraires:liste_itineraires' %}" class="btn btn-primary"
      >Cancel</a
    >
    {% endbuttons %}
  </form>
</div>

{% endblock content %}

topoguide/itineraires/templates/itineraires/navBar.html
{# Definition de la barre de navigation qui sera sur toutes les pages #}

{% extends 'base.html' %} 
{% load static %}

{% block body %}

<nav class="navbar navbar-dark bg-dark static-top">
  <div class="container-fluid">
    <div class="navbar-nav d-flex flex-row me-auto" >
      <a class="navbar-brand" href="#">TOPOGUIDE</a>
      <a class="nav-link active" aria-current="page" href={% url 'itineraires:liste_itineraires' %}>Itinéraires</a>
    </div>

    {# Formulaire de saisi du trie et du mot clé de recherche #}
    <div class="navbar-nav d-flex flex-row me-auto">
      <form method="POST" action={% url 'itineraires:searchResults' "all" %}>
        {% csrf_token %}
        

        {# Filtre de recherche à l'aide d'un mot clé #}
        <label for="search"></label>
        <input type="search" id="search" name="search" placeholder="Search...">
        
        {# Bouton de la validation du formulaire #}
        <input type="submit" value="OK">

      </form>
    </div>
    
    {% if user.is_authenticated %}
    <a name="" id="loginButton" class="btn btn-warning float-right mt-auto" href={% url 'logout' %} role="button" >Logout</a>
    {% else %}
    <a name="" id="loginButton" class="btn btn-success float-right mt-auto" href={% url 'login' %} role="button">Login</a>
    {% endif %}

  </div>
</nav>

{% block content %}{% endblock content %}

{% endblock body %}

topoguide/itineraires/templates/itineraires/searchResults.html
{# Page d'affichage de la recherche #}

{% extends 'itineraires/navBar.html' %} 
{% load static %}

{# En tête de la page #}
{% block content %}

<div class="container mt-3">
    <h1>Résulats de la recherche</h1>

    <form method="POST" action={% url 'itineraires:searchResults' "filtre" %} >
        {% csrf_token %}
        <div class="input-group mb-3">
            <button class="btn btn{% if filtre_models.0 == False %}-outline{%endif%}-primary" type="button" ><a style="color:black;" href={% url 'itineraires:searchResults' "filtre-sortie"%}>Sorties</a></button>
            <button class="btn btn{% if filtre_models.1 == False%}-outline{%endif%}-primary" type="button"><a style="color:black;" href={% url 'itineraires:searchResults' "filtre-itineraires"%}>Itineraires</a></button>
            <button class="btn btn{% if filtre_models.2 ==  False%}-outline{%endif%}-primary" type="button"><a style="color:black;" href={% url 'itineraires:searchResults' "filtre-commentaires"%}>Commentaires</a></button>
            <input type="search" id="search-filtre" name="search-filtre" class="form-control" value={{key_word}}>
            <button class="btn btn-success" type="submit">Go</button> 
        </div>
    </form>
    
</div>

    <div class="container mt-3">
    
    <p> Mot-clé: "{{key_word|truncatechars:15}}" --- Trie: "{{trie}}" </p>


        <div class="navbar-nav d-flex flex-row me-auto">
    
      <form method="POST" action={% url 'itineraires:searchResults' "trie" %}>
        {% csrf_token %}
        <div class="input-group mb-3">
        {# trie de trie à appliquer à la recherche #}
        <!--(si trie mais aucune recherche on affiche tous les résulats)-->
        <span class="input-group-text">Trier</span>
        <select name="trie" id="trie" class="form-select">
          <option value="aucun">Aucun</option>
          {% if last_filtre_models.0 or last_filtre_models.2 %}
          <optgroup label="Sorties/Commentaires">
            <option value="date-recente"{% if trie == "date-recente" %} selected {% endif %}>Date (Récente)</option>
            <option value="date-ancienne"{% if trie == "date-ancienne" %} selected {% endif %}>Date (Ancienne)</option>
          </optgroup>
          {% endif %}
          {% if last_filtre_models.1 %}
          <optgroup label="Itineraires">
            <option value="popularite-decroissante"{% if trie == "popularite-decroissante" %} selected {% endif %}>Popularité</option>
            <option value="difficultee-croissante-moy"{% if trie == "difficultee-croissante-moy" %} selected {% endif %}>Difficultee</option>
            <option value="duree-croissante-moy"{% if trie == "duree-croissante-moy" %} selected {% endif %}>Durée</option>
            <option value="niveau-exp-croissant-moy"{% if trie == "niveau-exp-croissant-moy" %} selected {% endif %}>Niveau d'expérience</option>
          </optgroup>
          {% endif %}
        </select>

        {# Bouton de la validation du formulaire #}
        <button class="btn btn-success" type="submit">OK</button>
        </div>
      </form>
    
    </div>

    {# Affichage de la liste d'itinéraires trouvée #}
    {% if liste_itinineraires and filtre_models.1%}
        <div class="container mt-3">
            <h2>Itinéraire(s) trouvé(s):</h2> 
            

            <div class="table-responsive"> 
                <table class="table table-bordered">
                    <thead class="table-dark">
                        <tr>
                            <th>Itinéraire</th>
                            <th>Durée</th>
                            <th>Difficulté</th>
                            {% if trie == "difficultee-croissante-moy" %}
                                <th>Difficulté réelle</th>
                            {% endif %}
                            {% if trie == "popularite-decroissante" %}
                                <th>Popularité</th>
                            {% endif %}
                            {% if trie == "duree-croissante-moy" %}
                                <th>Durée réelle</th>
                            {% endif %}
                            {% if trie == "niveau-exp-croissant-moy" %}
                                <th>Expérience moyenne</th>
                            {% endif %}
                            
                        </tr>
                    </thead>
                    
                    <tbody>
                        {% for itineraire_double in liste_itinineraires %}
                            {% if itineraire_double.6 %}
                                <tr classe="surlign">
                                    {% if itineraire_double.1 == "title" %}
                                        <td  classe="surlign" ><a href="{% url 'itineraires:detail' itineraire_double.0.id %}">
                                            <mark>{{ itineraire_double.0.nom }}</mark>
                                        </a></td>
                                    {% else %}
                                        <td><a href="{% url 'itineraires:detail' itineraire_double.0.id %}">
                                            {{ itineraire_double.0.nom }}
                                        </a></td>
                                    {% endif %}
                                    <td><a href="{% url 'itineraires:detail' itineraire_double.0.id %}">
                                        {{ itineraire_double.0.duree }}
                                    </a></td>
                                    <td><a href="{% url 'itineraires:detail' itineraire_double.0.id %}">
                                        {{ itineraire_double.0.difficulte }}/5
                                    </a></td>
                                    {% if trie == "difficultee-croissante-moy" %}
                                        <td><a href="{% url 'itineraires:detail' itineraire_double.0.id %}">
                                            {{ itineraire_double.2|floatformat:1 }}/5
                                        </a></td>
                                    {% endif %}
                                    {% if trie == "popularite-decroissante" %}
                                    <td><a href="{% url 'itineraires:detail' itineraire_double.0.id %}">
                                        {{ itineraire_double.3 }}
                                    </a></td>
                                    {% endif %}
                                    {% if trie == "duree-croissante-moy" %}
                                    <td><a href="{% url 'itineraires:detail' itineraire_double.0.id %}">
                                        {{ itineraire_double.4|time:"H\h i\m" }}
                                    </a></td>
                                    {% endif %}
                                    {% if trie == "niveau-exp-croissant-moy" %}
                                    <td><a href="{% url 'itineraires:detail' itineraire_double.0.id %}">
                                        {{ itineraire_double.5|floatformat:1 }}/3
                                    </a></td>
                                    {% endif %}

                                </tr>
                            {% endif %}
                        </a>

                            {% if itineraire_double.1 == "description" %}
                                <tr>
                                    <td></td>
                                    <th>Description</th>
                                    <td><mark>{{ itineraire_double.0.description }}</mark></td>
                                </tr>
                            {% endif %}

                            {% if itineraire_double.1 == "pointDeDepart" %}
                            <tr>
                                <td></td>
                                <th>Point De Depart</th>
                                <td><mark>{{ itineraire_double.0.pointDeDepart }}</mark></td>
                            </tr>
                            {% endif %}

                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% endif %}

    {# Affichage de la liste de sorties trouvée #}
    {% if liste_sorties and filtre_models.0 %}
        <div class="container mt-3">
            <h2>Sortie(s) trouvée(s):</h2>

            <div class="table-responsive"> 
                <table class="table table-bordered">
                    <thead class="table-dark">
                        <tr>
                            <th>Randonneur</th>
                            <th>Itineraires correspondant</th>
                            <th>Durée</th>
                            <th>Difficulté ressentie</th>
                            <th>Date d'ajout</th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for sortie_double in liste_sorties %}

                            <tr classe="surlign">
                                <td><a href="{% url 'itineraires:sortie' sortie_double.0.id %}">
                                    <mark>{{ sortie_double.0.randonneur }}</mark>
                                </a></td>
                                <td><a href="{% url 'itineraires:sortie' sortie_double.0.id %}">
                                    {{ sortie_double.0.itineraire }}
                                </a></td>
                                <td><a href="{% url 'itineraires:sortie' sortie_double.0.id %}">
                                    {{ sortie_double.0.duree }}
                                </a></td>
                                <td><a href="{% url 'itineraires:sortie' sortie_double.0.id %}">
                                    {{ sortie_double.0.difficulte}}/5
                                </a></td>
                                <td><a href="{% url 'itineraires:sortie' sortie_double.0.id %}">
                                    {{ sortie_double.0.date_sortie }}
                                </a></td>
                                <td>
                                    {% if request.user == sortie_double.0.randonneur %}
                                        <a class="btn btn-outline-warning" href={% url 'itineraires:modification_sortie' sortie_double.0.id%} >Modifier</a>
                                        <a class="btn btn-outline-danger" href={% url 'itineraires:suppression_sortie' sortie_double.0.id%} >Delete</a>
                                    {% endif %}
                                </td>
                            </tr>

                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

    {% endif %}

    {% if liste_commentaires and filtre_models.2 %}
        <div class="container mt-3">

            <h2>Commentaires(s) trouvé(s):</h2>
            {% for commentaire in liste_commentaires %}
                <li class="list-group-item border-0">
                <ul class="list-group list-group-horizontal">
                    <li class="list-group-item list-group-item-primary">{{commentaire.0.utilisateur}}</li>
                    <li class="list-group-item list-group-item-secondary">{{commentaire.0.date}}</li>
                    <li class="list-group-item list-group-item-primary">
                        <a href="{% url 'itineraires:detail' commentaire.0.itineraire_id %}">
                        {{commentaire.0.itineraire}}</a></li>
                    <li class="list-group-item">{{commentaire.0.texte|linebreaks|safe}}</li>
                </ul>
                </li>
            {% endfor %}
        </div>

    {% endif %}

    {# Si rien n'a été trouvé #}
    {% if not liste_itinineraires  and not liste_sorties %}
        <p>Rien ne correspond à "{{ key_word }}"</p>
    {% endif %}

</div>

{% endblock content %}

topoguide/itineraires/templates/itineraires/sorties.html
{% extends 'itineraires/navBar.html' %} {% block content %}
<div class="container-fluid !direction !spacing">
  <h1>{{ object.itineraire.nom }}</h1>
  <p>Durée: {{ object.duree }}</p>
  <p>Difficulté ressentie: {{ object.difficulte }}</p>
  <p>Date de sortie: {{ object.date_sortie}}</p>
  <p>Experience des participants : {{ object.experience }}</p>
  <p>Météo : {{ object.meteo }}</p>
</div>
{% endblock content %}